# Generated by Django 4.1.1 on 2022-09-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Цена"),
        ),
    ]
